// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NSQProducer is an autogenerated mock type for the NSQProducer type
type NSQProducer struct {
	mock.Mock
}

// Publish provides a mock function with given fields: topic, body
func (_m *NSQProducer) Publish(topic string, body []byte) error {
	ret := _m.Called(topic, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(topic, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
