version: '3'

services:
  redis:
    image: redis:5.0.5-alpine
    ports:
      - "6379:6379"

  nsqd:
    image: nsqio/nsq:v0.3.8
    command: /nsqd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq:v0.3.8
    ports:
      - "4171:4171"
    command: /nsqadmin --nsqd-http-address=nsqd:4151

  driver-location:
    image: driver-location
    links:
      - nsqd:nsqd
    ports:
      - "8010:8010"

  gateway:
    image: gateway
    ports:
      - "8000:8000"

  zombie-driver:
    image: zombie-driver
    ports:
      - "8020:8020"
