urls:
  - path: "/drivers/{id}/locations"
    method: "PATCH"
    nsq:
      topic: "locations"
      message:
        command: "update-driver-locations"

    # Improvement: make message building more flexible via a template:
    # message_template:
    #   command: "update-driver-locations"
    #   data:
    #     driver_id: "{request_vars.id}"
    #     coordinates: "{request_body}"

  - path: "/drivers/{id}"
    method: "GET"
    http:
      host: "zombie-driver:8020"

http_server:
  port: 8000
  shutdown_timeout: "5s"

nsq:
  daemon_address: "nsqd:4150"
