urls:
  - path: "/drivers/{id}/locations"
    method: "PATCH"
    nsq:
      topic: "locations"
      message:
        command: "update-driver-locations"

  - path: "/drivers/{id}"
    method: "GET"
    http:
      host: "zombie-driver"
