// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	context "context"

	driverloc "github.com/heetch/georgysavva-technical-test/driver-location/pkg/driverloc"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// GetterService is an autogenerated mock type for the GetterService type
type GetterService struct {
	mock.Mock
}

// GetLocations provides a mock function with given fields: ctx, driverID, timeInterval
func (_m *GetterService) GetLocations(ctx context.Context, driverID string, timeInterval time.Duration) ([]*driverloc.Location, error) {
	ret := _m.Called(ctx, driverID, timeInterval)

	var r0 []*driverloc.Location
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) []*driverloc.Location); ok {
		r0 = rf(ctx, driverID, timeInterval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*driverloc.Location)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, driverID, timeInterval)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
