// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	context "context"

	driverloc "github.com/heetch/georgysavva-technical-test/driver-location/pkg/driverloc"
	mock "github.com/stretchr/testify/mock"
)

// UpdaterService is an autogenerated mock type for the UpdaterService type
type UpdaterService struct {
	mock.Mock
}

// UpdateLocations provides a mock function with given fields: ctx, driverID, coordinates
func (_m *UpdaterService) UpdateLocations(ctx context.Context, driverID string, coordinates *driverloc.Coordinates) error {
	ret := _m.Called(ctx, driverID, coordinates)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *driverloc.Coordinates) error); ok {
		r0 = rf(ctx, driverID, coordinates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
