app:
  zombie_predicate:
    distance_threshold: 500 # In meters.
    time_interval: "5m"

driver_location_service:
  base_url: "http://driver-location:8010"

http_server:
  port: 8020
  shutdown_timeout: "5s"
