app:
  driver_locations_limit: 1000

redis:
  address: "redis:6379"

http_server:
  port: 8010
  shutdown_timeout: "5s"

nsq:
  topic: "locations"
  channel: "driver-location-service"
  daemon_addresses:
    - "nsqd:4150"
  workers_num: 16
