// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	context "context"

	zombiedriver "github.com/georgysavva/driver-app/zombie-driver/pkg/zombiedriver"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetDriver provides a mock function with given fields: ctx, driverID
func (_m *Service) GetDriver(ctx context.Context, driverID string) (*zombiedriver.Driver, error) {
	ret := _m.Called(ctx, driverID)

	var r0 *zombiedriver.Driver
	if rf, ok := ret.Get(0).(func(context.Context, string) *zombiedriver.Driver); ok {
		r0 = rf(ctx, driverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zombiedriver.Driver)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, driverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
